version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "1313:1313"
    entrypoint: [ "hugo","server", "--themesDir", "../..", "--appendPort=false", "--baseUrl=https://hugo.shopemaa.com" ]
